--1
GO
CREATE TRIGGER Products_INSERT_UPDATE
ON dbo.Orders
AFTER INSERT, UPDATE
AS
UPDATE Orders
SET Price = Price + Price * 0.38
WHERE Id = (SELECT Id FROM inserted)
--2
GO
CREATE TRIGGER Workers_INSERT_UPDATE
ON dbo.Workers
AFTER INSERT, UPDATE
AS
UPDATE Workers
SET Salary = Salary + Salary * 0.38
WHERE Id = (SELECT Id FROM inserted)
--3
GO
CREATE TRIGGER RepairInvoices_INSERT_UPDATE
ON dbo.RepairInvoices
AFTER INSERT, UPDATE
AS
UPDATE RepairInvoices
SET Cost = Cost + Cost * 0.38
WHERE Id = (SELECT Id FROM inserted)
--4
GO
CREATE TRIGGER Loog1
ON dbo.BuildingMaterials
AFTER INSERT
AS
INSERT INTO LoggingClasses(Logging)
SELECT Count
FROM INSERTED
--5
GO
CREATE TRIGGER Loog2
ON dbo.Customers
AFTER INSERT
AS
INSERT INTO LoggingClasses(Logging)
SELECT PhoneNumber
FROM INSERTED
--6
GO
CREATE TRIGGER Loog3
ON dbo.Orders
AFTER INSERT
AS
INSERT INTO LoggingClasses(Logging)
SELECT Price
FROM INSERTED
--7
GO
CREATE TRIGGER Loog4
ON dbo.Workers
AFTER INSERT
AS
INSERT INTO LoggingClasses(Logging)
SELECT Salary
FROM INSERTED
--8
GO
CREATE TRIGGER Loog5
ON dbo.Orders
AFTER UPDATE
AS
INSERT INTO LoggingClasses(Logging)
SELECT CONCAT( DateOnly, Price)
FROM inserted 